apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-starter-nextjs
  labels:
    app: gke-starter-nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-starter-nextjs
  template:
    metadata:
      labels:
        app: gke-starter-nextjs
    spec:
      serviceAccountName: cloudsql
      containers:
      - name: gke-starter-nextjs
        image: <IMAGE_PLACEHOLDER>
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /login
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: gke-starter-nextjs-secrets
                key: DATABASE_URL
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: gke-starter-nextjs-secrets
                key: JWT_SECRET
