apiVersion: batch/v1
kind: Job
metadata:
  name: gke-starter-nextjs-db-migrations
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: migrations
        image: <MIGRATION_IMAGE_PLACEHOLDER>
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: gke-starter-nextjs-secrets
                key: DATABASE_URL
      restartPolicy: Never
